esphome:
    name: hpsu-uart
    friendly_name: HPSU.UART
    platformio_options:
        build_unflags:
            - "-std=gnu++11"
            - "-fno-rtti"
        build_flags:
            - "-std=gnu++17"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source: github://wrfz/esphome-components@dev
    components: [daikin_rotex_uart]
    refresh: 0s

logger:
  level: INFO

api:
  encryption:
    key: !secret hpsu_uart_api_encryption_key

ota:
  platform: esphome
  password: !secret hpsu_uart_ota_password

web_server:
  version: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: DaikinRotex Fallback Hotspot
    password: H3jGqANSa7aL

captive_portal:

time:
  - platform: homeassistant

debug:
  update_interval: 5s

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Seconds
  - platform: uptime
    type: timestamp
    name: Uptime Timestamp
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID

button:
  - platform: restart
    name: "Rotex ESP Restart"
  - platform: template
    name: Dump Partitions
    on_press:
      - lambda: dump_partitions();

uart:
  id: uart_bus
  tx_pin: GPIO12
  rx_pin: GPIO11
  baud_rate: 9600
  parity: EVEN
  data_bits: 8
  stop_bits: 1

daikin_rotex_uart:
  id: rotext_hpsu_uart
  uart_id: uart_bus
  outdoor_unit: RRLQ008CAV3 # also supported: RRLQ011CAW1
  entities:
    t_liquid:
      name: Temperatur Fl체ssigkeitsleitung
    expansion_valve:
      name: Expansionsventil
    heat_exchanger_mid_temp:
      name: Lamellenw채rmetauscher Temperatur
    fan_speed:
      name: Ventilatordrehzahl
    discharge_pipe_temp:
      name: Temperatur nach K채ltemittelverdichter
    inv_frequency_rps:
      name: Kompressor Drehzahl
    inv_primary_current:
      name: INV Primary Current (A)
    dhw_tank_temp_r5t:
      name: DHW tank temp
    leaving_water_temp_before_buh:
      name: Vorlauftemeratur (TV)
    leaving_water_temp_after_buh:
      name: Vorlauftemeratur (TVBH)
    inlet_water_temp_r4t:
      name: R체cklauftemperatur
    outdoor_air_temp_r1t:
      name: Outdoor Air Temp
