name: Wokwi UART Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-esp:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Node.js and Wokwi CLI
      run: |
        sudo apt update
        sudo apt install -y git npm
        git clone https://github.com/wokwi/wokwi-cli
        cd wokwi-cli
        npm install
        sudo npm link

    - name: Install dependencies
      run: |
        pip install esphome pytest pyserial

    - name: Run Wokwi simulation
      run: |
        wokwi-cli exec \
          --project=./wokwi-project \
          --command="pytest tests/test_uart.cpp --disable-warnings"