name: Test Daikin Rotex UART Component

on:
  push:
    branches:
      - wokwi
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PlatformIO
      uses: platformio/action-core@v2

    - name: Run tests
      run: platformio test